### PR TITLE
Some minor improvements

### PR DESCRIPTION
**Pull request by willrogers**
* Use generics (we're not trying to support versions of Java < 1.5 I assume)
* Resolve some Maven warnings

### CODE REVIEW

**Comment by shroffk** [comment]
Actually someone on had complained that we should not "unnecessarily" require the use of newer versions of java when we don't need their features...
The readme therefor lists java 1.4 as the minimum requirement.

However, with your support I can make an argument that with the current version of java being 11. We should keep these libraries upto date to ensure their survival.

Can you update the readme.md to list java 8 as the minimum requirement.

**Comment by willrogers** [comment]
I don't think anyone could argue with Java 1.5. The pom specifies 'source 1.8 target 1.8', so we aren't actually checking compatibility anyway at the moment. It turns out I used `<>` which is only there in 1.7.

We could easily support back to 1.5 or 1.7 for the time being.

**Comment by willrogers** [comment]
Although it looks to me like we lost compatibility with 61aba39d23a00ead704a7563b04397a8bece479f anyway. I'm not sure I understand the way the README is restructured because I can't see how to compile for an older version of Java than the version the sources are compatible with.

@jlmuir changed this in 61aba39d23a00ead704a7563b04397a8bece479f. Am I wrong?

**Comment by shroffk** [comment]
> The pom specifies 'source 1.8 target 1.8'  
I think I might have started this... I think we can just say that java 8 is the minimum version required.

**Comment by willrogers** [comment]
Sorry, the second commit mentioned should have been bac4b6d508a163c9867ba47ad1ad04308095d7e7.

**Comment by kasemir** [comment]
For a fundamental EPICS library like CA I can understand that we want to support a somewhat older version of Java, not requiring the latest. But Java 8 should be acceptable since we really need to use the `Instant` instead of some EPICS time stamp class.

I see no urgent need to require Java 9/10/11, unless I'm missing something in there that would help.

Once there's a Java update with data-only classes ('records', 'value objects') that would be helpful for storing data without class overhead, we can think about requiring a move up to that.

**Pull request merged**
