### PR TITLE
Make echoTimeout configurable

### PR DESCRIPTION
**Pull request by ralphlange**
Make the echo timeout (to decide if an IOC is unresponsive) a configurable parameter.

### CODE REVIEW

**Comment by kasemir** [comment]
Looks good to me.
@shroffk , do you want to include the open JCA PRs in the epicsCoreJava update?

**Comment by shroffk** [comment]
Yes, I intend to include all of ITER's PR's into this release if possible

**Review by shroffk — APPROVED** [review]

**Comment by kasemir** [comment]
@ralphlange , now that you can configure the EPICS_CA_ECHO_TIMEOUT, how are you using that?
What value have you found that's better than the default?

**Comment by ralphlange** [comment]
I was not able to reproduce the behavior in a lab setup with reasonable effort. (Probably needs the right combination of machine power vs. network bandwidth.) So we have been testing this in production.
In that system, which before was reliably getting into the stalled situation within a few hours, a setting of 25000 (25sec) instead of the default 5sec has been working fine for a few weeks now.
They're in active commissioning, so they won't let us do more experiments at this time.

But I would generally claim that the analysis of the problem was correct and relaxing the timeout value for the "ping" sent to the IOC after beacons are missing avoids the issue.

**Comment by kasemir** [comment]
We have some PVs briefly turn UNDEFINED/Disconnected, then fine again.
With a display, nobody would notice, but with the alarm server, that can become a latched alarm that requires acknowledgement.
Haven't had time to look into it but wonder if it's similarly fixed by extending the echo timeout.

**Pull request merged**
