### PR TITLE
Merge caj

### PR DESCRIPTION
**Pull request by shroffk**
#7 
@ralphlange happy now? :)

### CODE REVIEW

**Comment by ralphlange** [comment]
Very happy now.
Two thumbs up!

**Comment by shroffk** [comment]
@berryma4 @kasemir is this ok to merge...just want a go ahead

**Comment by ralphlange** [comment]
Does it work?
I mean, do we have tests, or - if not - did you try using it?

**Comment by shroffk** [comment]
well it "works"
I can run the unit test locally with 100+ succeeding, 15 failures, and 8 errors.

**Comment by shroffk** [comment]
With the integration tests in place I will merge this

**Pull request merged**
