### PR TITLE
Switch from Travis-CI to GitHub Actions

### PR DESCRIPTION
**Pull request by ralphlange**
ssia

### CODE REVIEW

**Comment by ralphlange** [comment]
I think this is ready now...

**Comment by shroffk** [comment]
@ralphlange should we just skip jdk16 for the time being ( we keep the issue ticket open to document all that you have done )

**Comment by ralphlange** [comment]
Your call.

I configured it to not fail the build and kept it so we always have it on our radar that there is an issue to be fixed.
If you prefer not to see that - fine with me.

**Comment by shroffk** [comment]
Could you comment out the jdk16 inclusion - this was the comments remain in place as a reminder but the CI for the main project appears green.
I can't updated your branch so I am pushing this back to you :)
Thanks again

**Comment by ralphlange** [comment]
I don't understand.

Again: I added the configuration to have that job *not* fail the build. I.e., the CI for the main project appears green even though the Java 16 build is failing. (See https://github.com/ralphlange/jca/actions/runs/2703430640 for an example.)

**Comment by shroffk** [comment]
the thing is all PR's will have the "some failing" bit... which is what I was referring to.
In anycase...I have merged it for the time being... if it causes confusion with future PR's then it I will go and comment it out.
Thanks!

**Comment by ralphlange** [comment]
Thanks!
I'm fine with hiding the failures should they cause confusion. (I would still rather have them fixed than hidden.)

**Pull request merged**
