### PR TITLE
update readme to latest release 4.7

### PR DESCRIPTION
**Pull request by shroffk**

### CODE REVIEW

**Comment by shroffk** [comment]
@ralphlange seems to not be ignoring the jdk 16 failures.. I thought I saw a commit where GHA were told to ignore jdk16 build failures

**Comment by ralphlange** [comment]
What makes you think that?

https://github.com/epics-base/jca/actions shows that the two recent builds are marked as green, i.e., the Java 16 failures have been ignored.

**Review by ralphlange — APPROVED** [review]
Looks fine to me.

**Comment by shroffk** [comment]
image

I am trying to get this to turn to a green tick

**Comment by shroffk** [comment]
image

the following looks like a github bug
image

because the https://github.com/epics-base/jca/actions/workflows/build.yml/badge.svg is correct

**Comment by ralphlange** [comment]
The build does not stop, the Actions page shows it as successful, the badge on the home page is green. (Did you refresh https://github.com/epics-base/jca ?)

Ignoring a failure doesn't make a build successful. If you want to hide the fact that Java 16 builds don't work, you will have to remove the tests.

**Pull request merged**
