### PR TITLE
#6 updating the readme instructions

### PR DESCRIPTION
**Pull request by shroffk**
@kasemir @ralphlange @slominskir 
Does this read better?

### CODE REVIEW

**Comment by kasemir** [comment]
Fine, but includes a specific version number, so would require updates with each version.
Just link to e.g. https://repo1.maven.org/maven2/org/epics/jca instead of ...../2.4.2?

**Comment by shroffk** [comment]
I was hoping to avoid a section "latest release" which then lists the latest version...this way people are directed to the last release. I can add a link "archived/previous releases".
Also, the maven one with the version number allows people to directly copy/paste into the pom.

**Comment by ralphlange** [comment]
The pom snippet (same for other build systems) is also visible on some Maven repository sites.
What about linking to e.g.
https://mvnrepository.com/artifact/org.epics/jca
Click on the version, and you see the snippet.

**Comment by shroffk** [comment]
added the link to the mvn repo instead of the snippet.

**Pull request merged**
